### ISSUE TITLE
Pose2Video

### ISSUE THREAD

**Issue by zhou-linpeng** [YanzuoLu/CFLD#4]
Hi,
Thanks for releasing this amazing program! 
Do you have any plans to expand UNET from 2D to 3D and realize pose to video generation? like animate-anyone

**Comment by YanzuoLu** [comment]
It would be an interesting idea to expand the current approach into 3D or video generation.
To be honest, we are still in a very preliminary stage that is researching in the datasets and data volumes that need to be used, etc. You may also know that the training dataset of animate anyone is not public 😢 
We are worried that the current model capacity (this should be fine since we can use SDXL) and data are not enough to support better results.
Nevertheless, we welcome the exchange of more ideas. Thanks for your attention to our work.
